import { __ } from '@wordpress/i18n';

const defaultText = {
    'cancel': __('Cancel', 'wp-module-staging'),
    'clone': __('Clone', 'wp-module-staging'),
    'cloneConfirm': __('Confirm Clone Action', 'wp-module-staging'),
    'cloneDescription': __('This will overwrite anything in staging and update it to an exact clone of the current production site. Are you sure you want to proceed?', 'wp-module-staging'),
    'cloneNoticeCompleteText': __('Cloned to Staging', 'wp-module-staging'),
    'cloneNoticeStartText': __('Cloning production to staging, this should take about a minute.', 'wp-module-staging'),
    'cloneStagingSite': __('Clone to staging', 'wp-module-staging'),
    'created': __('Created', 'wp-module-staging'),
    'createNoticeCompleteText': __('Staging Created', 'wp-module-staging'),
    'createNoticeStartText': __('Creating a staging site, this should take about a minute.', 'wp-module-staging'),
    'createStagingSite': __('Create staging site', 'wp-module-staging'),
    'currentlyEditing': __('Currently editing', 'wp-module-staging'),
    'delete': __('Delete', 'wp-module-staging'),
    'deleteConfirm': __('Confirm Delete', 'wp-module-staging'),
    'deleteDescription': __('This will permanently delete staging site. Are you sure you want to proceed? You can recreate another staging site at any time, but any specific changes you\'ve made to this staging site will be lost.', 'wp-module-staging'),
    'deleteNoticeCompleteText': __('Deleted Staging', 'wp-module-staging'),
    'deleteNoticeStartText': __('Deleting the staging site, this should take about a minute.', 'wp-module-staging'),
    'deleteSite': __('Delete Staging Site', 'wp-module-staging'),
    'deploy': __('Deploy', 'wp-module-staging'),
    'deployAll': __('Deploy all changes', 'wp-module-staging'),
    'deployConfirm': __('Confirm Deployment', 'wp-module-staging'),
    'deployDatabase': __('Deploy database only', 'wp-module-staging'),
    'deployDescription': __('This will deploy staging to production and overwrite current production site. Are you sure you want to proceed?', 'wp-module-staging'),
    'deployFiles': __('Deploy files only', 'wp-module-staging'),
    'deployNoticeCompleteText': __('Deployed', 'wp-module-staging'),
    'deployNoticeStartText': __('Deploying from staging to production, this should take about a minute.', 'wp-module-staging'),
    'deploySite': __('Deploy Site', 'wp-module-staging'),
    'error': __('Error', 'wp-module-staging'),
    'noStagingSite': __("You don't have a staging site yet.", 'wp-module-staging'),
    'notCurrentlyEditing': __('Not currently editing', 'wp-module-staging'),
    'proceed': __('Proceed', 'wp-module-staging'),
    'productionSiteTitle': __('Production Site', 'wp-module-staging'),
    'stagingSiteTitle': __('Staging Site', 'wp-module-staging'),
    'subTitle': __('A staging site is a duplicate of your live site, offering a secure environment to experiment, test updates, and deploy when ready.', 'wp-module-staging'),
    'switch': __('Switch', 'wp-module-staging'),
    'switching': __('Switching', 'wp-module-staging'),
    'switchToProduction': __('Switch to Production', 'wp-module-staging'),
    'switchToProductionDescription': __('This will navigate you to the production environment', 'wp-module-staging'),
    'switchToProductionNoticeCompleteText': __('Loading the production environment now.', 'wp-module-staging'),
    'switchToProductionNoticeStartText': __('Switching to the production environment, this should take about a minute.', 'wp-module-staging'),
    'switchToStaging': __('Switch to Staging', 'wp-module-staging'),
    'switchToStagingDescription': __('This will navigate you to the staging environment', 'wp-module-staging'),
    'switchToStagingNoticeCompleteText': __('Loading the staging environment now.', 'wp-module-staging'),
    'switchToStagingNoticeStartText': __('Switching to the staging environment, this should take about a minute.', 'wp-module-staging'),
    'title': __('Staging', 'wp-module-staging'),
    'unknownErrorMessage': __('An unknown error has occurred.', 'wp-module-staging'),
    'working': __('Working...', 'wp-module-staging'),
};

export default defaultText;